server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: process-app
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: preferred_username
            authorization-uri: ${KEYCLOAK_REDIRECT_URI}

mirror:
  backend: ${BACKEND_API_URL}
  auth.issuer.validate: false