server:
  port: 8060
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
spring:
  security:
    oauth2:
        client:
          registration:
            keycloak:
              client-id: process-app
              authorization-grant-type: authorization_code
              scope:
                - openid
              client-secret: KSCJ8Te7XcZQqhVD7EYYDV1rDdn9E26U
          provider:
            keycloak:
              issuer-uri: http://localhost:8088/realms/process-org
              user-name-attribute: preferred_username