services:
  DB:
    container_name: process-service-data
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=process
    ports:
      - "5432:5432"
    networks:
      - process
    restart: always

  KEYCLOAK:
    container_name: process-service-keycloak
    image: quay.io/keycloak/keycloak:24.0.3
    command: start-dev --import-realm
    ports:
      - "8088:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realms:/opt/keycloak/data/import
    networks:
      - process
    restart: always

  API:
    container_name: process-service-api
    image: process-service-api:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - DB
    links:
      - DB
      - KEYCLOAK
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://DB:5432/process
      DB_KEY: passw0rd
      KEYCLOAK_ISSUER_URI: http://keycloak:8080
    networks:
      - process

  UI:
    container_name: process-service-ui
    image: process-service-ui:0.0.1
    ports:
      - "80:8080"
    depends_on:
      - KEYCLOAK
    links:
      - KEYCLOAK
      - API
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KEYCLOAK_CLIENT_SECRET: '**********'
      KEYCLOAK_ISSUER_URI: http://keycloak:8080
      BACKEND_API_URL: http://API:8080
    networks:
      - process

  MOCK:
    container_name: process-service-mock
    image: process-service-mock:0.0.1
    ports:
      - "8081:8080"

networks:
  process:
    driver: bridge
