version: '3'
services:
  FREEPDB1:
    container_name: FREEPDB1
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=process
    ports:
      - "5432:5432"
    networks:
      - process
    restart: always

  KEYCLOAK:
    image: quay.io/keycloak/keycloak:24.0.3
    command: start-dev --import-realm
    ports:
      - "8088:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-local.json:/opt/keycloak/data/import/realm-local.json
    networks:
      - process
    restart: always

  API:
    image: process-service-api:0.0.1
    ports:
      - "8080:8080"
    links:
      - FREEPDB1
      - KEYCLOAK
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://FREEPDB1:5432/process
      DB_KEY: passw0rd
      KEYCLOAK_CLIENT_SECRET: AOA1Q29svqRWlrz2jDcxNPT3YrPG0niX
      KEYCLOAK_ISSUER_URI: http://KEYCLOAK:8080/realms/PSM-Auth
    networks:
      - process


networks:
  process:
    driver: bridge
