version: '3'
services:
  FREEPDB1:
    container_name: FREEPDB1
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=process
    ports:
      - "5432:5432"
    networks:
      - process
    restart: always
networks:
  process:
    driver: bridge
