server:
  port: 8888
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/process
    username: process
    password: passw0rd
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

springdoc:
  swagger-ui:
    path: /

ibm:
  mq:
    channel: DEV.ADMIN.SVRCONN
    conn-name: localhost(4414)
    user: admin
    password: passw0rd
    sendingQueueName: DEV.QUEUE.1
    receivingQueueName: DEV.QUEUE.1
    queue-manager: QM1
