server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/process
    username: process
    password: passw0rd
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  security:
    type: none
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8088/realms/process-org
springdoc:
  swagger-ui:
    path: /

