apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  KEYCLOAK_ADMIN: Yjk2YTFmYWYtMDkyMi00YWNhLTg1YmItMjU4M2YyOTMzZDZm
  KEYCLOAK_CLIENT_SECRET: QzlsRnlza0thNkd4cEZaVHg1YnptZW1KdERIYjU2eU8=
# b96a1faf-0922-4aca-85bb-2583f2933d6f